// Regenerate with `GIT_NOTES_WRITE_BINDINGS=1 cargo test bindings` in src-tauri/.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getAppInfo: () => typedError<AppInfo, AppError>(__TAURI_INVOKE("get_app_info")),
	getSettings: () => typedError<Settings, AppError>(__TAURI_INVOKE("get_settings")),
	updateSettings: (settings: Settings) => typedError<Settings, AppError>(__TAURI_INVOKE("update_settings", { settings })),
	listNotebooks: () => typedError<NotebookInfo[], AppError>(__TAURI_INVOKE("list_notebooks")),
	defaultNotebooksDir: () => typedError<string, AppError>(__TAURI_INVOKE("default_notebooks_dir")),
	/**  Creates `parent_dir/name` (defaults to the platform notebooks dir) and registers it. */
	createNotebook: (name: string, parentDir: string | null) => typedError<NotebookInfo, AppError>(__TAURI_INVOKE("create_notebook", { name, parentDir })),
	/**  Registers an existing folder (picked with the system dialog) as a notebook. */
	openNotebook: (path: string) => typedError<NotebookInfo, AppError>(__TAURI_INVOKE("open_notebook", { path })),
	/**  Removes the notebook from the list; files on disk are untouched. */
	forgetNotebook: (notebookId: string) => typedError<null, AppError>(__TAURI_INVOKE("forget_notebook", { notebookId })),
	listTree: (notebookId: string) => typedError<TreeNode[], AppError>(__TAURI_INVOKE("list_tree", { notebookId })),
	readFile: (notebookId: string, path: string) => typedError<FileContent, AppError>(__TAURI_INVOKE("read_file", { notebookId, path })),
	/**  Writes the file atomically and returns its new modification time (ms since epoch). */
	writeFile: (notebookId: string, path: string, text: string) => typedError<WriteResult, AppError>(__TAURI_INVOKE("write_file", { notebookId, path, text })),
	createFile: (notebookId: string, path: string) => typedError<string, AppError>(__TAURI_INVOKE("create_file", { notebookId, path })),
	createDir: (notebookId: string, path: string) => typedError<string, AppError>(__TAURI_INVOKE("create_dir", { notebookId, path })),
	/**  Renames or moves a file/folder. Returns the normalized new path. */
	renameEntry: (notebookId: string, from: string, to: string) => typedError<string, AppError>(__TAURI_INVOKE("rename_entry", { notebookId, from, to })),
	deleteEntry: (notebookId: string, path: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_entry", { notebookId, path })),
	/**  Stores pasted image bytes under `assets/` and returns the Markdown to insert. */
	saveAsset: (notebookId: string, notePath: string, fileName: string, bytes: number[]) => typedError<SavedAsset, AppError>(__TAURI_INVOKE("save_asset", { notebookId, notePath, fileName, bytes })),
	/**  Copies a file dropped from the desktop into `assets/`. */
	importAsset: (notebookId: string, notePath: string, sourcePath: string) => typedError<SavedAsset, AppError>(__TAURI_INVOKE("import_asset", { notebookId, notePath, sourcePath })),
	/**  Starts emitting [`NotebookChanged`] events for the notebook (idempotent). */
	watchNotebook: (notebookId: string) => typedError<null, AppError>(__TAURI_INVOKE("watch_notebook", { notebookId })),
	unwatchNotebook: (notebookId: string) => typedError<null, AppError>(__TAURI_INVOKE("unwatch_notebook", { notebookId })),
};

/** Events */
export const events = {
	notebookChanged: makeEvent<NotebookChanged>("notebook-changed"),
};

/* Types */
/**
 *  Serializable application error. Every command returns `Result<T, AppError>`.
 * 
 *  Variants are tagged by `kind` so the frontend can branch on them without string matching.
 */
export type AppError = { kind: "io"; message: string } | { kind: "git"; message: string } | { kind: "auth"; message: string } | { kind: "invalidInput"; message: string } | { kind: "notFound"; message: string } | { kind: "alreadyExists"; message: string } | { kind: "internal"; message: string };

/**  Static information about the running app, used by the About/diagnostics UI. */
export type AppInfo = {
	version: string,
	platform: string,
	arch: string,
	deviceName: string,
	libgit2Version: string,
	debug: boolean,
};

export type EditorFont = "sans" | "serif" | "mono";

export type EntryKind = "file" | "dir";

export type FileContent = {
	path: string,
	text: string,
	/**  Last modification time in milliseconds since the Unix epoch. */
	modifiedMs: number,
};

/**  Emitted (debounced) when files inside a watched notebook change on disk. */
export type NotebookChanged = {
	notebookId: string,
	/**  Notebook-relative paths; empty string when the change could not be attributed. */
	paths: string[],
};

export type NotebookInfo = {
	/**  Stable identifier derived from the canonical path. */
	id: string,
	name: string,
	/**  Absolute path on disk. Shown to the user, never used by the frontend for I/O. */
	path: string,
};

export type SavedAsset = {
	/**  Notebook-relative path of the stored file, e.g. `assets/screenshot-20261002-1530.png`. */
	path: string,
	/**  Markdown snippet to insert into the note (link is relative to the note's directory). */
	markdown: string,
};

export type Settings = {
	theme: ThemeMode,
	editorFont: EditorFont,
	/**  Editor body size in CSS pixels. */
	editorFontSize: number,
	/**  Desktop sidebar width in CSS pixels. */
	sidebarWidth: number,
	/**  Notebook to reopen on launch. */
	lastNotebookId: string | null,
};

export type ThemeMode = "system" | "light" | "dark";

export type TreeNode = {
	name: string,
	/**  Notebook-relative path with `/` separators. */
	path: string,
	kind: EntryKind,
	/**  Always present (empty for files) so the TypeScript type stays a single shape. */
	children: TreeNode[],
};

/**  Result of a write: the file's new modification time, used to detect external edits. */
export type WriteResult = {
	modifiedMs: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

